# Site settings
title: Blog of Andrew Jacob Pietila
email: me@ajp.xyz
description: "I am Andrew Jacob Pietila. This is my blog."
baseurl: ""
url: "http://ajp.xyz"
twitter_username: ralliasubernerd
github_username:  rallias

# Build settings
markdown: kramdown
permalink: pretty

collections:
  rfcs:
    output: true
    permalink: /rfcs/
    collection: "RFC's gone CRAZY!"